### ISSUE TITLE
Issues with installing matplotlib

### ISSUE THREAD

**Issue by banningjoe** [DeepLabCut/DeepLabCut-core#12]
Specs:
OS: Windows 10
Graphics card: RTX3070
CUDA: 9.0
Python: 3.9

Due to series 3000 cards not working with Tensorflow 1.x, I'm trying to run the headless DeepLabCut with tensorflow 2.0. 

Issue:
When I make a fresh anaconda environment and run: pip install git+https://github.com/DeepLabCut/DeepLabCut-core.git@tf2.2alpha
(code I retrieved from the colab), I am unable to install matplotlib.

```
>>>pip install git+https://github.com/DeepLabCut/DeepLabCut-core.git@tf2.2alpha
Collecting git+https://github.com/DeepLabCut/DeepLabCut-core.git@tf2.2alpha
  Cloning https://github.com/DeepLabCut/DeepLabCut-core.git (to revision tf2.2alpha) to c:\users\jc\appdata\local\temp\pip-req-build-r3dhdv6n
Collecting certifi
  Using cached certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
Collecting chardet
  Using cached chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Collecting click
  Using cached click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting easydict
  Using cached easydict-1.9.tar.gz (6.4 kB)
Collecting h5py~=2.7
  Using cached h5py-2.10.0.tar.gz (301 kB)
Collecting intel-openmp
  Using cached intel_openmp-2021.1.2-py2.py3-none-win_amd64.whl (3.3 MB)
Collecting imgaug
  Using cached imgaug-0.4.0-py2.py3-none-any.whl (948 kB)
Collecting ipython
  Using cached ipython-7.19.0-py3-none-any.whl (784 kB)
Collecting ipython-genutils
  Using cached ipython_genutils-0.2.0-py2.py3-none-any.whl (26 kB)
Collecting matplotlib==3.0.3
  Using cached matplotlib-3.0.3.tar.gz (36.6 MB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\JC\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\JC\\AppData\\Local\\Temp\\pip-install-cy4dervr\\matplotlib\\setup.py'"'"'; __file__='"'"'C:\\Users\\JC\\AppData\\Local\\Temp\\pip-install-cy4dervr\\matplotlib\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\JC\AppData\Local\Temp\pip-pip-egg-info-wqn2llym'
         cwd: C:\Users\JC\AppData\Local\Temp\pip-install-cy4dervr\matplotlib\
    Complete output (47 lines):
    ============================================================================
    Edit setup.cfg to change the build options

    BUILDING MATPLOTLIB
                matplotlib: yes [3.0.3]
                    python: yes [3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020,
                            17:08:21) [MSC v.1927 64 bit (AMD64)]]
                  platform: yes [win32]

    REQUIRED DEPENDENCIES AND EXTENSIONS
                     numpy: yes [not found. pip may install it below.]
          install_requires: yes [handled by setuptools]
                    libagg: yes [pkg-config information for 'libagg' could not
                            be found. Using local copy.]
                  freetype: no  [The C/C++ header for freetype
                            (freetype2\ft2build.h) could not be found.  You may
                            need to install the development package.]
                       png: no  [The C/C++ header for png (png.h) could not be
                            found.  You may need to install the development
                            package.]
                     qhull: yes [pkg-config information for 'libqhull' could not
                            be found. Using local copy.]

    OPTIONAL SUBPACKAGES
               sample_data: yes [installing]
                  toolkits: yes [installing]
                     tests: no  [skipping due to configuration]
            toolkits_tests: no  [skipping due to configuration]

    OPTIONAL BACKEND EXTENSIONS
                       agg: yes [installing]
                     tkagg: yes [installing; run-time loading from Python Tcl /
                            Tk]
                    macosx: no  [Mac OS-X only]
                 windowing: yes [installing]

    OPTIONAL PACKAGE DATA
                      dlls: no  [skipping due to configuration]

    ============================================================================
                            * The following required packages can not be built:
                            * freetype, png
                            * Please check http://gnuwin32.sourceforge.net/packa
                            * ges/freetype.htm for instructions to install
                            * freetype
                            * Please check http://gnuwin32.sourceforge.net/packa
                            * ges/libpng.htm for instructions to install png
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
I've tried installing freetype and libpng libraries. However, I only run into more errors once I have done that. Any idea what the issue is here?

Joe

**Comment by PlatinumYao** [comment]
I got the same issue when I tried to "pip install git+https://github.com/DeepLabCut/DeepLabCut-core.git@tf2.2alpha" in a new conda environment. I just "conda install matplotlib" manually before I stall the DLC-Core.

**Comment by banningjoe** [comment]
Hi PlatinumYao, 

Thanks for your reply. I've tried this. 
After "conda install matplotlib", when I run "pip install git+https://github.com/DeepLabCut/DeepLabCut-core.git@tf2.2alpha"
I get the following error:
```
ERROR: Command errored out with exit status 1:
     command: 'C:\Users\JC\.conda\envs\Jan12Test\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\JC\\AppData\\Local\\Temp\\pip-install-8mi7jwzd\\moviepy_2687a2f35d6e475784da01618c9a2796\\setup.py'"'"'; __file__='"'"'C:\\Users\\JC\\AppData\\Local\\Temp\\pip-install-8mi7jwzd\\moviepy_2687a2f35d6e475784da01618c9a2796\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\JC\AppData\Local\Temp\pip-pip-egg-info-i_2hg4xk'
         cwd: C:\Users\JC\AppData\Local\Temp\pip-install-8mi7jwzd\moviepy_2687a2f35d6e475784da01618c9a2796\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\JC\AppData\Local\Temp\pip-install-8mi7jwzd\moviepy_2687a2f35d6e475784da01618c9a2796\setup.py", line 3, in <module>
        import ez_setup
    ModuleNotFoundError: No module named 'ez_setup'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
So, then I "pip install ez_setup".

When I rerun "pip install git+https://github.com/DeepLabCut/DeepLabCut-core.git@tf2.2alpha", I get the following error:
```
ERROR: Command errored out with exit status 1:
     command: 'C:\Users\JC\.conda\envs\Jan12Test\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\JC\\AppData\\Local\\Temp\\pip-install-cxsjmcit\\moviepy_94b255f71b6f421698868161129debbb\\setup.py'"'"'; __file__='"'"'C:\\Users\\JC\\AppData\\Local\\Temp\\pip-install-cxsjmcit\\moviepy_94b255f71b6f421698868161129debbb\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\JC\AppData\Local\Temp\pip-pip-egg-info-j3o1ho5n'
         cwd: C:\Users\JC\AppData\Local\Temp\pip-install-cxsjmcit\moviepy_94b255f71b6f421698868161129debbb\
    Complete output (31 lines):
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.14.tar.gz
    Traceback (most recent call last):
      File "C:\Users\JC\.conda\envs\Jan12Test\lib\site-packages\ez_setup.py", line 143, in use_setuptools
        raise ImportError
    ImportError

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\JC\AppData\Local\Temp\pip-install-cxsjmcit\moviepy_94b255f71b6f421698868161129debbb\setup.py", line 4, in <module>
        ez_setup.use_setuptools()
      File "C:\Users\JC\.conda\envs\Jan12Test\lib\site-packages\ez_setup.py", line 145, in use_setuptools
        return _do_download(version, download_base, to_dir, download_delay)
      File "C:\Users\JC\.conda\envs\Jan12Test\lib\site-packages\ez_setup.py", line 123, in _do_download
        tarball = download_setuptools(version, download_base,
      File "C:\Users\JC\.conda\envs\Jan12Test\lib\site-packages\ez_setup.py", line 193, in download_setuptools
        src = urlopen(url)
      File "C:\Users\JC\.conda\envs\Jan12Test\lib\urllib\request.py", line 222, in urlopen
        return opener.open(url, data, timeout)
      File "C:\Users\JC\.conda\envs\Jan12Test\lib\urllib\request.py", line 531, in open
        response = meth(req, response)
      File "C:\Users\JC\.conda\envs\Jan12Test\lib\urllib\request.py", line 640, in http_response
        response = self.parent.error(
      File "C:\Users\JC\.conda\envs\Jan12Test\lib\urllib\request.py", line 569, in error
        return self._call_chain(*args)
      File "C:\Users\JC\.conda\envs\Jan12Test\lib\urllib\request.py", line 502, in _call_chain
        result = func(*args)
      File "C:\Users\JC\.conda\envs\Jan12Test\lib\urllib\request.py", line 649, in http_error_default
        raise HTTPError(req.full_url, code, msg, hdrs, fp)
    urllib.error.HTTPError: HTTP Error 403: SSL is required
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Any thoughts?
