### ISSUE TITLE
deeplabcutcore import error(RTX3070)

### ISSUE THREAD

**Issue by sasaki-iwateJapn** [DeepLabCut/DeepLabCut-core#14]
Hello everyone
I have a issue.
I install deeplabcutcore and packages when I import Deeplabcutcore occur no module error 'tensorflow.contrib'
what I do next?
 
(DLC-GPU) C:\Windows\system32>pip list
Package                  Version
------------------------ --------------------
-                        nsorflow-gpu
-ensorflow-gpu           2.3.0
absl-py                  0.11.0
argon2-cffi              20.1.0
astor                    0.8.1
astunparse               1.6.3
async-generator          1.10
attrs                    20.3.0
backcall                 0.2.0
bayesian-optimization    1.2.0
bleach                   3.2.1
cachetools               4.2.0
certifi                  2020.12.5
cffi                     1.14.4
chardet                  4.0.0
click                    7.1.2
colorama                 0.4.4
cycler                   0.10.0
Cython                   0.29.21
decorator                4.4.2
deeplabcut-core          0.0b0
deeplabcutcore           0.0b3
defusedxml               0.6.0
easydict                 1.9
entrypoints              0.3
filterpy                 1.4.5
gast                     0.3.3
google-auth              1.24.0
google-auth-oauthlib     0.4.2
google-pasta             0.2.0
grpcio                   1.31.0
h5py                     2.10.0
idna                     2.10
imageio                  2.9.0
imageio-ffmpeg           0.4.3
imgaug                   0.4.0
importlib-metadata       2.0.0
intel-openmp             2021.1.2
ipykernel                5.3.4
ipython                  7.19.0
ipython-genutils         0.2.0
ipywidgets               7.6.3
jedi                     0.18.0
Jinja2                   2.11.2
joblib                   1.0.0
jsonschema               3.2.0
jupyter                  1.0.0
jupyter-client           6.1.7
jupyter-console          6.2.0
jupyter-core             4.7.0
jupyterlab-pygments      0.1.2
jupyterlab-widgets       1.0.0
Keras-Applications       1.0.8
Keras-Preprocessing      1.1.2
kiwisolver               1.3.1
llvmlite                 0.34.0
Markdown                 3.3.3
MarkupSafe               1.1.1
matplotlib               3.0.3
mistune                  0.8.4
mkl-fft                  1.2.0
mkl-random               1.1.1
mkl-service              2.3.0
mock                     4.0.3
moviepy                  1.0.1
msgpack                  1.0.2
msgpack-numpy            0.4.7.1
nb-conda                 2.2.1
nb-conda-kernels         2.3.1
nbclient                 0.5.1
nbconvert                6.0.7
nbformat                 5.0.8
nest-asyncio             1.4.3
networkx                 2.5
notebook                 6.1.6
numba                    0.51.1
numexpr                  2.7.2
numpy                    1.16.4
oauthlib                 3.1.0
opencv-python            3.4.13.47
opencv-python-headless   4.5.1.48
opt-einsum               3.3.0
packaging                20.8
pandas                   1.1.5
pandocfilters            1.4.3
parso                    0.8.1
patsy                    0.5.1
pickleshare              0.7.5
Pillow                   8.1.0
pip                      20.3.3
proglog                  0.1.9
prometheus-client        0.9.0
prompt-toolkit           3.0.8
protobuf                 3.13.0
psutil                   5.8.0
pyasn1                   0.4.8
pyasn1-modules           0.2.8
pycparser                2.20
Pygments                 2.7.4
pyparsing                2.4.7
pyreadline               2.1
pyrsistent               0.17.3
python-dateutil          2.8.1
pytz                     2020.5
PyWavelets               1.1.1
pywin32                  227
pywinpty                 0.5.7
PyYAML                   5.3.1
pyzmq                    20.0.0
qtconsole                4.7.7
QtPy                     1.9.0
requests                 2.25.1
requests-oauthlib        1.3.0
rsa                      4.7
ruamel.yaml              0.16.12
ruamel.yaml.clib         0.2.2
scikit-image             0.17.2
scikit-learn             0.24.0
scipy                    1.4.1
Send2Trash               1.5.0
setuptools               51.1.2.post20210112
Shapely                  1.7.1
six                      1.15.0
statsmodels              0.12.1
tables                   3.6.1
tabulate                 0.8.7
tb-nightly               1.14.0a20190301
tensorboard              2.4.1
tensorboard-plugin-wit   1.7.0
tensorflow               2.3.0
tensorflow-estimator     2.3.0
tensorflow-gpu-estimator 2.3.0
tensorpack               0.9.8
termcolor                1.1.0
terminado                0.9.2
testpath                 0.4.4
tf-estimator-nightly     1.14.0.dev2019030115
tf-slim                  1.1.0
threadpoolctl            2.1.0
tifffile                 2021.1.11
tornado                  6.1
tqdm                     4.56.0
traitlets                5.0.5
urllib3                  1.26.2
wcwidth                  0.2.5
webencodings             0.5.1
Werkzeug                 1.0.1
wheel                    0.36.2
widgetsnbextension       3.5.1
wincertstore             0.2
wrapt                    1.12.1
wxPython                 4.0.4
zipp                     3.4.0

(DLC-GPU) C:\Windows\system32>python
Python 3.7.9 (default, Aug 31 2020, 17:10:11) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
Failed calling sys.__interactivehook__
Traceback (most recent call last):
  File "C:\Users\htomi\anaconda3\envs\DLC-GPU\lib\site.py", line 408, in register_readline
    import readline
  File "C:\Users\htomi\anaconda3\envs\DLC-GPU\lib\site-packages\readline.py", line 6, in <module>
    from pyreadline.rlmain import Readline
  File "C:\Users\htomi\anaconda3\envs\DLC-GPU\lib\site-packages\pyreadline\__init__.py", line 12, in <module>
    from . import logger, clipboard, lineeditor, modes, console
  File "C:\Users\htomi\anaconda3\envs\DLC-GPU\lib\site-packages\pyreadline\modes\__init__.py", line 3, in <module>
    from . import emacs, notemacs, vi
  File "C:\Users\htomi\anaconda3\envs\DLC-GPU\lib\site-packages\pyreadline\modes\emacs.py", line 15, in <module>
    import pyreadline.lineeditor.history as history
  File "C:\Users\htomi\anaconda3\envs\DLC-GPU\lib\site-packages\pyreadline\lineeditor\history.py", line 257
    q.add_history(RL("aaaa"),encoding='utf8'))
                                             ^
SyntaxError: invalid syntax
>>> import deeplabcutcore
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\htomi\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcutcore\__init__.py", line 20, in <module>
    from deeplabcutcore.create_project import create_new_project, create_new_project_3d, add_new_videos, load_demo_data
  File "C:\Users\htomi\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcutcore\create_project\__init__.py", line 4, in <module>
    from deeplabcutcore.create_project.demo_data import load_demo_data
  File "C:\Users\htomi\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcutcore\create_project\demo_data.py", line 14, in <module>
    from deeplabcutcore.utils import auxiliaryfunctions
  File "C:\Users\htomi\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcutcore\utils\__init__.py", line 1, in <module>
    from deeplabcutcore.utils.make_labeled_video import *
  File "C:\Users\htomi\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcutcore\utils\make_labeled_video.py", line 38, in <module>
    from deeplabcutcore.pose_estimation_tensorflow.config import load_config
  File "C:\Users\htomi\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcutcore\pose_estimation_tensorflow\__init__.py", line 13, in <module>
    from deeplabcutcore.pose_estimation_tensorflow.nnet import *
  File "C:\Users\htomi\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcutcore\pose_estimation_tensorflow\nnet\__init__.py", line 16, in <module>
    from deeplabcutcore.pose_estimation_tensorflow.nnet.pose_net import *
  File "C:\Users\htomi\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcutcore\pose_estimation_tensorflow\nnet\pose_net.py", line 9, in <module>
    import tensorflow.contrib.slim as slim
ModuleNotFoundError: No module named 'tensorflow.contrib'
>>> ^Z

(DLC-GPU) C:\Windows\system32>ipython
Python 3.7.9 (default, Aug 31 2020, 17:10:11) [MSC v.1916 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.19.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import deeplabcutcore
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-5cd872217571> in <module>
----> 1 import deeplabcutcore

~\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcutcore\__init__.py in <module>
     18
     19
---> 20 from deeplabcutcore.create_project import create_new_project, create_new_project_3d, add_new_videos, load_demo_data
     21 from deeplabcutcore.create_project import create_pretrained_project, create_pretrained_human_project
     22 from deeplabcutcore.generate_training_dataset import extract_frames, select_cropping_area

~\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcutcore\create_project\__init__.py in <module>
      2 from deeplabcutcore.create_project.new_3d import create_new_project_3d
      3 from deeplabcutcore.create_project.add import add_new_videos
----> 4 from deeplabcutcore.create_project.demo_data import load_demo_data
      5 from deeplabcutcore.create_project.modelzoo import create_pretrained_human_project, create_pretrained_project

~\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcutcore\create_project\demo_data.py in <module>
     12 from pathlib import Path
     13 import deeplabcutcore
---> 14 from deeplabcutcore.utils import auxiliaryfunctions
     15
     16 def load_demo_data(config,createtrainingset=True):

~\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcutcore\utils\__init__.py in <module>
----> 1 from deeplabcutcore.utils.make_labeled_video import *
      2 from deeplabcutcore.utils.auxiliaryfunctions import *
      3 from deeplabcutcore.utils.video_processor import *
      4 from deeplabcutcore.utils.plotting import *
      5

~\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcutcore\utils\make_labeled_video.py in <module>
     36
     37 from deeplabcutcore.utils import auxiliaryfunctions
---> 38 from deeplabcutcore.pose_estimation_tensorflow.config import load_config
     39 from skimage.util import img_as_ubyte
     40 from skimage.draw import circle_perimeter, circle, line,line_aa

~\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcutcore\pose_estimation_tensorflow\__init__.py in <module>
     11 from deeplabcutcore.pose_estimation_tensorflow.dataset import *
     12 from deeplabcutcore.pose_estimation_tensorflow.models import *
---> 13 from deeplabcutcore.pose_estimation_tensorflow.nnet import *
     14 from deeplabcutcore.pose_estimation_tensorflow.util import *
     15

~\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcutcore\pose_estimation_tensorflow\nnet\__init__.py in <module>
     14 from deeplabcutcore.pose_estimation_tensorflow.nnet.losses import *
     15 from deeplabcutcore.pose_estimation_tensorflow.nnet.net_factory import *
---> 16 from deeplabcutcore.pose_estimation_tensorflow.nnet.pose_net import *
     17 from deeplabcutcore.pose_estimation_tensorflow.nnet.predict import *

~\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcutcore\pose_estimation_tensorflow\nnet\pose_net.py in <module>
      7 import re
      8 import tensorflow as tf
----> 9 import tensorflow.contrib.slim as slim
     10 from tensorflow.contrib.slim.nets import resnet_v1
     11 from deeplabcutcore.pose_estimation_tensorflow.dataset.pose_dataset import Batch

ModuleNotFoundError: No module named 'tensorflow.contrib'

**Comment by sasaki-iwateJapn** [comment]
Could it be that only googlecolaboratory?

**Comment by MMathisLab** [comment]
`ModuleNotFoundError: No module named 'tensorflow.contrib'` this 110% means you are using the work TF version, i.e. 1.x
